"""add team to users

Revision ID: 0365cdaaf7e7
Revises: 893632ab8720
Create Date: 2026-09-02 14:01:20.534784
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0365cdaaf7e7'
down_revision: str | None = '893632ab8720'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the type explicitly so this migration does not depend on the
    # dialect deciding to emit CREATE TYPE as a side effect of add_column.
    team_enum = postgresql.ENUM(
        'EXECUTIVE', 'CORE', 'MEMBER', name='team_enum', create_type=False
    )
    team_enum.create(op.get_bind(), checkfirst=True)

    # Existing rows become MEMBER, which is the safe default: nobody is
    # silently promoted into the executive or core listing.
    op.add_column(
        'users',
        sa.Column('team', team_enum, server_default='MEMBER', nullable=False),
    )
    op.create_index('ix_users_team', 'users', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_team', table_name='users')
    op.drop_column('users', 'team')
    postgresql.ENUM(name='team_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
