"""initial schema

Revision ID: 893632ab8720
Revises: 
Create Date: 2026-08-18 15:38:38.845666
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '893632ab8720'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Case-insensitive email uniqueness.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_buckets',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_index('ix_rate_limit_expiry', 'rate_limit_buckets', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('member_id', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='user_status_enum'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index('ix_users_status_role', 'users', ['status', 'role'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('accuracy_threshold_meters', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('attendance_start_time', sa.Time(), nullable=False),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_close_after_hours', sa.Integer(), nullable=False),
    sa.Column('max_travel_speed_kmh', sa.Integer(), nullable=False),
    sa.Column('block_impossible_movement', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy_threshold_meters >= 5 AND accuracy_threshold_meters <= 1000', name='ck_workspace_accuracy'),
    sa.CheckConstraint('auto_close_after_hours >= 1 AND auto_close_after_hours <= 72', name='ck_workspace_autoclose'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_workspace_lat'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_workspace_lng'),
    sa.CheckConstraint('max_travel_speed_kmh >= 10 AND max_travel_speed_kmh <= 5000', name='ck_workspace_speed'),
    sa.CheckConstraint('radius_meters >= 10 AND radius_meters <= 5000', name='ck_workspace_radius'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_workspaces_single_active', 'workspaces', ['active'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('attendance_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'PRESENT', 'CHECKED_OUT', name='day_status_enum'), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.Column('first_punch_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_punch_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_seconds >= 0', name='ck_attendance_day_total'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_date', name='uq_attendance_day_user_date')
    )
    op.create_index('ix_attendance_days_date', 'attendance_days', ['work_date'], unique=False)
    op.create_index('ix_attendance_days_user_date', 'attendance_days', ['user_id', 'work_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'TOKEN_REFRESH_REUSE', 'PASSWORD_CHANGED', 'PUNCH_IN_SUCCESS', 'PUNCH_IN_REJECTED', 'PUNCH_OUT_SUCCESS', 'PUNCH_OUT_REJECTED', 'LOCATION_PERMISSION_FAILURE', 'SUSPICIOUS_MOVEMENT', 'SESSION_AUTO_CLOSED', 'USER_CREATED', 'USER_UPDATED', 'USER_DISABLED', 'USER_ENABLED', 'USER_ROLE_CHANGED', 'USER_PASSWORD_RESET', 'WORKSPACE_UPDATED', 'ADMIN_ATTENDANCE_EDIT', 'REPORT_EXPORTED', 'RATE_LIMIT_TRIGGERED', name='audit_action_enum'), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', name='audit_result_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_actor_time', 'audit_logs', ['actor_user_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_target_time', 'audit_logs', ['target_user_id', 'timestamp'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_day_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('punch_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'AUTO_CLOSED', 'MANUAL', name='session_status_enum'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(punch_out IS NULL) = (duration_seconds IS NULL)', name='ck_session_duration_pairing'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_session_duration_positive'),
    sa.CheckConstraint('punch_out IS NULL OR punch_out > punch_in', name='ck_session_order'),
    sa.ForeignKeyConstraint(['attendance_day_id'], ['attendance_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_day', 'attendance_sessions', ['attendance_day_id'], unique=False)
    op.create_index('ix_sessions_open', 'attendance_sessions', ['user_id'], unique=False, postgresql_where=sa.text('punch_out IS NULL'))
    op.create_index('ix_sessions_user_punch_in', 'attendance_sessions', ['user_id', 'punch_in'], unique=False)
    op.create_index('uq_one_open_session_per_user', 'attendance_sessions', ['user_id'], unique=True, postgresql_where=sa.text('punch_out IS NULL'))
    op.create_table('punch_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('IN', 'OUT', name='punch_type_enum'), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accuracy_meters', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('radius_snapshot', sa.Integer(), nullable=True),
    sa.Column('accuracy_threshold_snapshot', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.Enum('ACCEPTED', 'REJECTED', name='validation_enum'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('location_purged', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_punch_events_user_idempotency')
    )
    op.create_index('ix_punch_events_session', 'punch_events', ['session_id'], unique=False)
    op.create_index('ix_punch_events_user_time', 'punch_events', ['user_id', 'server_timestamp'], unique=False)
    op.create_index('ix_punch_events_validation', 'punch_events', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_punch_events_validation', table_name='punch_events')
    op.drop_index('ix_punch_events_user_time', table_name='punch_events')
    op.drop_index('ix_punch_events_session', table_name='punch_events')
    op.drop_table('punch_events')
    op.drop_index('uq_one_open_session_per_user', table_name='attendance_sessions', postgresql_where=sa.text('punch_out IS NULL'))
    op.drop_index('ix_sessions_user_punch_in', table_name='attendance_sessions')
    op.drop_index('ix_sessions_open', table_name='attendance_sessions', postgresql_where=sa.text('punch_out IS NULL'))
    op.drop_index('ix_sessions_day', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_target_time', table_name='audit_logs')
    op.drop_index('ix_audit_actor_time', table_name='audit_logs')
    op.drop_index('ix_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_days_user_date', table_name='attendance_days')
    op.drop_index('ix_attendance_days_date', table_name='attendance_days')
    op.drop_table('attendance_days')
    op.drop_index('uq_workspaces_single_active', table_name='workspaces', postgresql_where=sa.text('active'))
    op.drop_table('workspaces')
    op.drop_index('ix_users_status_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_rate_limit_expiry', table_name='rate_limit_buckets')
    op.drop_table('rate_limit_buckets')
    # ### end Alembic commands ###
