#!/usr/bin/env bash
#
# Builds the PWA against a given API URL and deploys it to Firebase Hosting.
#
#   ./scripts/deploy-firebase.sh https://your-tunnel.trycloudflare.com
#
# The API URL is compiled into the JavaScript bundle, so this has to be re-run
# every time the tunnel URL changes. That is the cost of a free quick tunnel; a
# named Cloudflare tunnel on your own domain gives a stable URL and removes it.
set -euo pipefail

cd "$(dirname "$0")/.."

API_URL="${1:-}"

# With no argument, use the URL the running tunnel recorded. This is the normal
# path: no copying, so no placeholder pasted by mistake.
if [ -z "${API_URL}" ] && [ -s .tunnel-url ]; then
  API_URL="$(tr -d '\n' < .tunnel-url)"
  echo "Using the tunnel URL from .tunnel-url: ${API_URL}"
fi

if [ -z "${API_URL}" ]; then
  echo "No API URL given and .tunnel-url is empty." >&2
  echo "Start the tunnel first:  npm run tunnel" >&2
  echo "or pass one explicitly:  $0 https://your-api-host" >&2
  exit 1
fi

API_URL="${API_URL%/}"          # strip a trailing slash
API_URL="${API_URL%/api/v1}"    # accept the URL with or without the prefix

case "${API_URL}" in
  https://*) ;;
  *)
    echo "The API URL must be https://" >&2
    echo "A page served over HTTPS cannot call an http:// address -- the" >&2
    echo "browser blocks it as mixed content. Run ./scripts/tunnel-api.sh" >&2
    exit 1
    ;;
esac

echo "Checking the API is reachable at ${API_URL} ..."
if ! curl -sf --max-time 10 "${API_URL}/api/v1/health" >/dev/null; then
  echo "No healthy API at ${API_URL}/api/v1/health" >&2
  echo "Start the backend and the tunnel first." >&2
  exit 1
fi

echo "Writing frontend/.env.production"
cat > frontend/.env.production <<CONF
# Generated by scripts/deploy-firebase.sh -- do not commit.
VITE_API_BASE_URL=${API_URL}/api/v1
CONF

echo "Building the PWA ..."
npm --prefix frontend run build

echo "Deploying to Firebase Hosting ..."
npx firebase deploy --only hosting

cat <<MSG

Deployed.

Check on the phone:
  1. open the hosting URL above
  2. sign in
  3. tap Punch in -- the browser will ask for location, because the page is
     finally on a secure origin

If sign-in fails, the usual causes are:
  * backend/.env still has the development settings -- it needs
    COOKIE_SECURE=true, COOKIE_SAMESITE=none and CORS_ORIGINS set to the
    Firebase origins (see backend/.env.firebase.example), then restart uvicorn
  * the tunnel was restarted and has a different URL -- re-run this script
MSG
