// Stable error codes shared with the backend. UI switches on these, never on
// message text.
export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_DISABLED: 'USER_DISABLED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  INVALID_COORDINATES: 'INVALID_COORDINATES',
  ACCURACY_TOO_LOW: 'ACCURACY_TOO_LOW',
  OUTSIDE_GEOFENCE: 'OUTSIDE_GEOFENCE',
  IMPOSSIBLE_MOVEMENT: 'IMPOSSIBLE_MOVEMENT',
  WORKSPACE_NOT_CONFIGURED: 'WORKSPACE_NOT_CONFIGURED',

  ALREADY_PUNCHED_IN: 'ALREADY_PUNCHED_IN',
  NO_ACTIVE_SESSION: 'NO_ACTIVE_SESSION',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Client-side only. Never sent by the server.
  OFFLINE: 'OFFLINE',
  NETWORK_ERROR: 'NETWORK_ERROR',
  LOCATION_PERMISSION_DENIED: 'LOCATION_PERMISSION_DENIED',
  LOCATION_UNAVAILABLE: 'LOCATION_UNAVAILABLE',
  LOCATION_TIMEOUT: 'LOCATION_TIMEOUT',
  LOCATION_UNSUPPORTED: 'LOCATION_UNSUPPORTED',
};

// Codes that mean "the punch did not happen, and the state on screen is stale".
export const RESYNC_CODES = new Set([
  ErrorCode.ALREADY_PUNCHED_IN,
  ErrorCode.NO_ACTIVE_SESSION,
  ErrorCode.DUPLICATE_REQUEST,
]);
